### ISSUE TITLE
question

### ISSUE THREAD

**Issue by LinuxpowerLudo** [cerlymarco/tsmoothie#1]
Hi Marco

First thank you for your python package !

Among all the smoother of the package which one is casual ? or are they all no casual ?

Regards 
Ludo

**Comment by cerlymarco** [comment]
Hi, thanks

what do you for 'casual' ?

**Comment by LinuxpowerLudo** [comment]
Marco,

Sometime smoother give you a no casual signal ... the output depends upon future inputs.. / data forward snooping.

**Comment by cerlymarco** [comment]
All are in this sense casual. The way they are casual depends on the algorithm adopted. To make them not casual you have to 'censor' the future and iterate the smoothing step by step (or by data intervals). if you want to iter step by step you can use the WindowWrapper which is compatible whit every smoother for 1D series

**Comment by LinuxpowerLudo** [comment]
Thanks your advices !
I need look your window wrapper 👍
