### ISSUE TITLE
Example WindowWrapper Signal

### ISSUE THREAD

**Issue by LinuxpowerLudo** [cerlymarco/tsmoothie#10]
Hi Marco,

I paste my code with a WindowWrapper example :

date_start='2000-01-01'
date_end='2021-01-01'
data = pdr.get_data_yahoo('AAPL', start=date_start, end=date_end)
CL = data['Close'].values
sm = []
window = 20
dzero = np.zeros((window - 1,), dtype=int)
smoother = WindowWrapper(ConvolutionSmoother(window_len=20, window_type='ones'), window_shape=window)
smoother.smooth(CL)
for i, (true, smooth) in enumerate(zip(smoother.Smoother.data, smoother.Smoother.smooth_data)):
    sm.append(smooth[-1])
sig = np.append(dzero, sm, axis=0)
data['SM'] = sig
plt.plot(data['Close'])
plt.plot(data['SM'])
plt.show()

Can you confirm me that is the right way for build a smooth signal without look ahead bias ?

Sorry but python isn't my native language :) 

Regards.
Ludo.

**Comment by cerlymarco** [comment]
Hi, yes it seems ok

Bye
