### ISSUE TITLE
accommodating replicates

### ISSUE THREAD

**Issue by ramesh8v** [cerlymarco/tsmoothie#11]
Hi Marco,

Thanks for creating this very useful package! 

Say I'm collecting data from a sensor over a set of time periods (24 hours) in two replicates. That means I have data from two different copies of the same type of sensor placed at the same place. Because of some experimental noise, we see some variation between values. My data looks like this, green is from one sensor, and the red is from other
![image](https://user-images.githubusercontent.com/12216865/118917379-9d3d6480-b8e5-11eb-9d00-b515031f4b02.png)
When I use my data in a smoother function, like a nested np array
```
smoother = LowessSmoother(smooth_fraction=0.1, iterations=1)
smoother.smooth(np.array([np.array(replicate1), np.array(replicate 2)]))
```
`smoother.smooth_data` has two arrays in a nested array, one for each replicate. How do I get a single value for each time point after fitting a curve?

**Comment by cerlymarco** [comment]
Hi, 

every smoother accepts data in this format (n_series, timesteps). The smoothing process returns an array of smoothed series of the same shape (n_series, timesteps). This is all you need to query all the information you want. 

All these kinds of information are reported in the documentation and you can also understand it from the notebook examples.

Best regards
