### ISSUE TITLE
Feature Engineering

### ISSUE THREAD

**Issue by firmai** [cerlymarco/tsmoothie#13]
Great package, could you perhaps provide a label to indicate whether a specific method can be used for data transformations (features), the reason I am asking is that some smoothers/filters are forward looking and would cause a forward looking bias. Tahnsk again :)

**Comment by cerlymarco** [comment]
Hi,

all the Smoothers available here have a forward-looking bias. If you want to smooth with a forward-looking bias you can use the WindowWrapper class.

If you support the project don't forget to live a star ;-)
