### ISSUE TITLE
Numpy rounding issue causes NaN array on Lowess prediction results

### ISSUE THREAD

**Issue by brunom63** [cerlymarco/tsmoothie#15]
Marco, thanks for the excellent project! You've made a great effort combining all  the smoothing theories in one single, easy-to-use library! I couldn't thank you enough!

I stumbled upon a rounding math problem today on the "prediction_interval" function.  This problem is actually not on your code, but instead on how Numpy chooses to round floating numbers on the numpy.sum method:

> For floating point numbers the numerical precision of sum (and np.add.reduce) is in general limited by directly adding each number individually to the result causing rounding errors in every step. However, often numpy will use a numerically better approach (partial pairwise summation) leading to improved precision in many use-cases. This improved precision is always provided when no axis is given. When axis is given, it will depend on which axis is summed. Technically, to provide the best speed possible, the improved precision is only used when the summation is along the fast axis in memory. Note that the exact precision may vary depending on other parameters. In contrast to NumPy, Python’s math.fsum function uses a slower but more precise approach to summation. Especially when summing a large number of lower precision floating point numbers, such as float32, numerical errors can become significant. In such cases it can be advisable to use dtype=”float64” to use a higher precision for the output.

This only occurred with a very particular set of numbers while using the LowessSmoother, which ended up with a negative value that caused an excepetion on the square root later on:

`mse = (np.square(resid).sum(axis=1, keepdims=True) / (N - d_free)).T`
....
`predstd = np.sqrt(predvar).T`

`tsmoothie\utils_func.py:306: RuntimeWarning: invalid value encountered in sqrt`

**Quick solution first:**

`mse = (np.square(resid).sum(axis=1, dtype="float64", keepdims=True) / (N - d_free)).T`

Adding the dtype parameter solved the problem. This causes numpy to increase rounding precision (as stated above) which ended up giving me the correct result.

Quick observation: As yet, I'm not quite sure on how adding dtype might affect speed and performance on all the other smoother methods, but I will have to check on this eventually.

**Explanation and info:**

While calling Lowess Smother method, setting the iterations parameter to any value greater than 1 caused the rounding numpy problem on the following set of data:

`data[6318, 36871, 39933, 22753, 9680, 6503, 4032, 2733, 2807, 2185, 1866, 1800, 1907, 1537, 1357, 1221, 1354, 1514, 2021, 11110, 17656, 17397, 24385, 22361, 18709, 20201, 20245, 25767, 21345, 18928, 20958, 20425, 23066, 20221, 18756, 17403, 17843, 21201, 25867, 17342, 16815, 5700, 25897, 20891, 20022, 22291, 24334, 21304, 25328, 22201, 20308, 21539, 29637, 22740, 19510, 18959, 21160, 23520, 20574, 16519, 18779]`

Problem occurs at data[-3]. The problem doesn't occur when I cut the rest out:

`data[0:len(data)-3]` 

At that point, the total sum causes numpy's rounding to go berserk, I imagine. 

This ends up calling the square root exception above, which in turn causes your "prediction_interval" function to return an array of NaN results:

`[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]]
[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]]`

Variable "mse" without dtype outputs:
`[[-35780673.18644068]]`

And after including dtype:
`[[35780673.18644068]]`

Other important parameters I used to help you check this were:
Prediction: prediction_interval
Confidence: 0.05
Smooth Fraction: 0.3
Batch Size: None
Didn't use a WindowWrapper

For this project I'm stuck with iterations between 5 and 6 and no Batch Size, I need to smooth the entire data together.

By the way, I think there something going on with the batch_size parameter also, but I haven't got time to look at it yet. 

Thanks again for the great project!! Keep up the good work!!

**Comment by cerlymarco** [comment]
Hi, thanks for your feedback...

The problem is due to the high magnitude of your data which doesn't suit the numpy float format. As you suggest, a possible solution is to cast the sum to the highest float type ('float64').

In my opinion, the best solution is to standardize/normalize the data before smoothing in order to reduce their magnitude.

Here is an example of the data and the configuration you provided. The magnitude is reduce dividing by the max and then the original series is restored multiply by the max:

```
from tsmoothie.smoother import LowessSmoother

x = np.asarray(
    [6318, 36871, 39933, 22753, 9680, 6503, 4032, 2733, 2807, 2185, 1866, 
     1800, 1907, 1537, 1357, 1221, 1354, 1514, 2021, 11110, 17656, 17397, 
     24385, 22361, 18709, 20201, 20245, 25767, 21345, 18928, 20958, 20425, 
     23066, 20221, 18756, 17403, 17843, 21201, 25867, 17342, 16815, 5700, 
     25897, 20891, 20022, 22291, 24334, 21304, 25328, 22201, 20308, 21539, 
     29637, 22740, 19510, 18959, 21160, 23520, 20574, 16519, 18779]
)
x_max = x.max()

smoother = LowessSmoother(smooth_fraction=0.3, iterations=6)
smoother.smooth(x/x_max)

low, up = smoother.get_intervals('prediction_interval', confidence=0.05)

plt.plot(x)
plt.plot(smoother.smooth_data[0]*x_max)
plt.plot(low[0]*x_max); plt.plot(up[0]*x_max)
```

![image](https://user-images.githubusercontent.com/36955807/132485501-84406fc3-e8f5-4f62-925a-2ad6e24197f2.png)

**Comment by brunom63** [comment]
Marco, yes, normalizing indeed fixes the problem.

Your insight actually helped me on another problem I was facing.

Thanks!

**Comment by brunom63** [comment]
Marco, me again. I'll just comment here because it's related. 

Bumped on a "true_division" warning yesterday at that same line (variable "mse").

Nothing related to your code again, just numpy. The real reason was that the data set was very small, less than 3 values.

For timeseries and many different set of data, stuff like that happens. Specially because I also do some analysis on small data sets. 

Any way, just to tell you that I added the following line to the code which made the annoying warning go away, although a validation of the data size before sending to the smooth functions is a much better aproach:

```
with np.errstate(invalid='ignore', divide='ignore'): 
    mse = (np.square(resid).sum(axis=1, dtype="float64", keepdims=True) / (N - d_free)).T 
```
