### ISSUE TITLE
Is there a way to extend the model past the data?

### ISSUE THREAD

**Issue by parksj10** [cerlymarco/tsmoothie#19]
This is a great library, thanks a lot! I have a question, is there a way to extend the smooth/CI past the data domain? See the below plot, aesthetically I would like the smooth regions to go to the edges of the graph region....

<img width="825" alt="image" src="https://user-images.githubusercontent.com/28692761/171905463-7e00ed9a-5574-4fa3-b00f-0dc50a4ae386.png">

**Comment by cerlymarco** [comment]
Hi, the smooth CI refers only to the seen data. you can't extend them outside
