### ISSUE TITLE
Smoothing without introducing look-ahead bias

### ISSUE THREAD

**Issue by brunofacca** [cerlymarco/tsmoothie#2]
Hello. Thanks for this great library.

I need to detrend a time series for usage with an ML forecasting model. The most important step is to isolate the trend. I've tried dozens of strategies and all of the ones that produce a smooth and accurate trend line (e.g., HP filter, STA, fitting a polynomial model, etc) introduce look-ahead bias in the data. Then there are the moving average strategies which do not introduce look-ahead bias but the trend line is either too laggy (if we set a large look-behind period) or too choppy (if we set a small look-behind period).

Do you think I could use any of your smoothers to isolate the trend without introducing any kind of lookahead bias? I'm thinking that a heavily smoothed version of the time series could be a good representation of the trend, then I'd just have to subtract the trend from the series. By "not introducing any kind of lookahead bias", I mean that it should:
* Produce the exact same result if applied in the entire time series or applied in an expanding window fashion (with step=1) and only using the last value of each window.
* The isolated trend of the past observations does not change when new (more recent) observations are introduced.

Thank you!

**Comment by cerlymarco** [comment]
Hi, thanks!

All the smoother (including also those implemented here) have a look-ahead bias. The strength of this bias depends on the algorithm adopted. To delate the bias you have to 'censor' the future and iterate the smoothing step by step (or by data intervals). Tsoomthie aims to reproduce the smoothing operation in a fast and vectorized way, this behavior can permit to operate the smoothing of the series step by step quickly

The choice of the smoothing algo is related to what you are trying to achieve

**Comment by brunofacca** [comment]
Hi Marco. 

I've tried all the algorithms available in the library and they really are extremely fast. Thanks again for open sourcing this.

Best regards.

**Comment by LinuxpowerLudo** [comment]
Hi Marco & Bruno,

I paste my code with a WindowWrapper example :

date_start='2000-01-01'
date_end='2021-01-01'
data = pdr.get_data_yahoo('AAPL', start=date_start, end=date_end)
CL = data['Close'].values
sm = []
window = 20
dzero = np.zeros((window - 1,), dtype=int)
smoother = WindowWrapper(ConvolutionSmoother(window_len=20, window_type='ones'), window_shape=window)
smoother.smooth(CL)
for i, (true, smooth) in enumerate(zip(smoother.Smoother.data, smoother.Smoother.smooth_data)):
    sm.append(smooth[-1])
sig = np.append(dzero, sm, axis=0)
data['SM'] = sig
plt.plot(data['Close'])
plt.plot(data['SM'])
plt.show()

Can you confirm me that is the right way for build a smooth signal without look ahead bias ?

Sorry but python isn't my native language :) 

Regards.
Ludo.
