### ISSUE TITLE
About component_noise in Kalman filter

### ISSUE THREAD

**Issue by tawdes** [cerlymarco/tsmoothie#21]
Hi Marco
I am new to Tsmootie and also Kalman filters. In a process to understand.
Have a doubt about component_noise. I have time series where daily seasonality is prominent. So mostly component noise: season= 0.1 works well (low sigma value as I am confident about daily seasonality). But I have tried values like 0.01 and 1 also for the same. I want to know is there any valid limits/ range for the sigma values of component_noise? i.e. 0 to 1 (0 to 100%) etc.

**Comment by cerlymarco** [comment]
Hi, every float >= 0 is supported like when defining the sigma param in a gaussian distribution

if you support the project don't forget to leave a star ;-)
