### ISSUE TITLE
question about gaussian smoother

### ISSUE THREAD

**Issue by JackSparrow-demonic** [cerlymarco/tsmoothie#26]
smoother-->regression_basis.gaussian_kernel(line 119), 
is it should be "X_base = - np.square(X[:, None] - knots) / (2 * sigma ** 2)" ?

**Comment by cerlymarco** [comment]
Hi, this behavior is intentional. If u want `sigma ** 2` pass `sigma ** 2` to `GaussianSmoother`.

If u support the project don't forget to leave a star ;-)
