### ISSUE TITLE
Would minding explaining what is long seasons is in Kalman smoother?

### ISSUE THREAD

**Issue by redemption-star** [cerlymarco/tsmoothie#27]

**Comment by cerlymarco** [comment]
Hi, 
"long seasons" stands for the cyclical component in the state-space representation
if you support the project, don't forget to leave a star ;-)

**Comment by redemption-star** [comment]
How does it differ from 'seasonality'?

**Comment by cerlymarco** [comment]
A seasonal pattern exists when a series is influenced by seasonal factors (e.g., the quarter of the year, the month, or day of the week). Seasonality is always of a fixed and known period. 

A cyclic pattern exists when data exhibit rises and falls that are not of fixed period. Think of business cycles which usually last several years, but where the length of the current cycle is unknown beforehand

All the best

**Comment by redemption-star** [comment]
Thank you for your explanation. I have four years of monthly sales data from Jan 2019 to Dec 2023 in China, which is strongly influenced by the breakout of covid-19, frequent lockdowns and eventual opening up in the end of 2022. You Kalman smoother helped me greatly. To further refine my algorithm, I'm thinking about incorporating long seasonality. Setting n_seasonality to 12 is reasonable and achieved good result. I am thinking about which n for long seasonality.
