### ISSUE TITLE
WindowWrapper behavior with ExponentialSmoother

### ISSUE THREAD

**Issue by meneghet** [cerlymarco/tsmoothie#3]
When I use the WindowWrapper in combination with LowessSmoother, like in the notebook example, I obtain the desired output (NxM numpy array, where N=samples and M=window size). However, when I use WindowWrapper with ExponentialSmoother i get a Nx1 numpy array.

Is this because ExponentialSmoother is an online-ready algorithm?

code:
https://ibb.co/GdBtWJv

**Comment by cerlymarco** [comment]
Hi, WindowWrapper smooths timeseries partitioning them into equal sliding. it accepts only univariate series in this format (timesteps,), (timesteps,1), (1,timesteps)

the size of the return arrays is related to the smoothing algo selected

generally, it returns smoothed windows of this size (timesteps-window_shape+1, window_len)

ExponentialSmoother is a special case. ExponentialSmoother returns by default (series, timesteps-window_len). for this reason, it's usage with WindowWrapper returns (timesteps-window_shape+1, window_shape-window_len). this is correct behavior. I suggest u to try before ExponentialSmoother to test its functionality

**Comment by meneghet** [comment]
I tried it before and I understand your explanation. It's maybe a bit counter-intuitive that different algorithms return different shapes but that's just my feedback for possible future improvements.

Thanks for sharing the package, Marco
