### ISSUE TITLE
Interoperability with sktime

### ISSUE THREAD

**Issue by mloning** [cerlymarco/tsmoothie#4]
Hi, 

Rather a discussion point than issue: I just saw your post on https://github.com/MaxBenChrist/awesome_time_series_in_python/issues/31 and I'd love to make sktime easily inter-operable with tsmoothie. Would you be interested in working on that?

**Comment by cerlymarco** [comment]
Hi, 

This would be great! How is it possible to do that?

Thanks

**Comment by mloning** [comment]
As far as I can see, the smoothing transformation in your package are series-to-series transformations, taking in a single series and returning the smoothed version of that series, is that true? 

If so, I see two options: either we wrap your library and provide an adapter in sktime, or you change your API to meet our specification. I'm not sure which one you're more comfortable with, happy to discuss either one in more detail. For series-to-series transformations, we follow the template/abstract base class here: https://github.com/alan-turing-institute/sktime/blob/79ac80ab65adb30fdf233e98433646c1989da2fc/sktime/transformations/base.py#L107

I'm happy to set up a call to discuss this in more detail if that would be helpful.

**Comment by cerlymarco** [comment]
Sorry for the delay in the response...

Yes, tsmoothie operates series-to-series transformations, this is true for univariate and multivariate time series.

I'm a little busy at the moment with other projects. Feel free to wrap my library following sktime code rules... If there'll be some particular problems or you'll need clarifications I would be happy to provide you support
