### ISSUE TITLE
enhance for tsmoothie to be applicable for inputs with multiple dimensions

### ISSUE THREAD

**Issue by turmeric-blend** [cerlymarco/tsmoothie#5]
Hi, thanks for this library.

Is it possible to vectorize across multiple dimensions? So a generic N dimensions (..., ..., ..., ..., , timesteps), currently it is limited to (series, timesteps). This would be useful to apply to multivariate time-series problems as well as deep learning applications where there is a `batch_size`. This should be fairly straight forward using PyTorch (actually even doable with numpy). Would there be a computation limitation?

**Comment by cerlymarco** [comment]
hi, thanks for your support

I know what you mean and I intentionally don't allow this behavior because in some situations this may result in memory errors during the smoothing operations. However, u can use the WindowWrapper for each time series and then stack the results. The example below shows how to smooth multiple time series to feed into an RNN (3D sequences)

```
data = sim_randomwalk(n_series=2, timesteps=200, 
                      process_noise=10, measure_noise=30)

serie1 = data[0]
smoother1 = WindowWrapper(ConvolutionSmoother(window_len=20, window_type='ones'), 
                         window_shape=30)
smoother1.smooth(serie1)

serie2 = data[1]
smoother2 = WindowWrapper(ConvolutionSmoother(window_len=20, window_type='ones'), 
                         window_shape=30)
smoother2.smooth(serie2)

seq_3d = np.stack([
    smoother1.Smoother.smooth_data,
    smoother2.Smoother.smooth_data
], axis=-1) ## (n_sample, timesteps, n_series)
```

**Comment by turmeric-blend** [comment]
Is it necessary to use `WindowWrapper`? I have a `tensor` with shape `(batch_size,series,timestep)` eg `(4,2,100)`. Can I instead loop over the `batch_size` and stack each batch after instead like so?:

```
smoother_function = ConvolutionSmoother(window_len=20, window_type='ones')

processed_tensors = []
for sample in tensor: # will loop 4 times corresponding to batch_size=4
     print(sample.shape) # --> shape: (2,100)
     processed_tensors.append(smoother_function(sample).smooth_data)
tensor = np.stack(processed_tensors) # shape (4,2,100)
```

**Comment by cerlymarco** [comment]
No it's not necessary if u have 3D arrays (I supposed u started from 2D arrays). The case u reported seems ok

**Comment by Zero-coder** [comment]
It's useful,thanks guys
