### ISSUE TITLE
Anomaly inference from smoothed data

### ISSUE THREAD

**Issue by nsankar** [cerlymarco/tsmoothie#6]
Thanks for developing this library. This is a pretty interesting one. I have a question when using tsmoothie as follows.  

Currently I am using an (unsupervised) clustering method to  create a model once on a large amount of data (that, assigns inlier and outlier labels) and then query the model repeatedly with small amounts of *new data* to predict the label (to infer anomaly).  

 I am planning to use tsmoothie for filtering the noise in the large input data which will be subject to clustering to assign inlier and outlier labels .  Later when I use new data points for predicting the normal or anomaly label, I should smooth that also before prediction. Is that correct?

**Comment by cerlymarco** [comment]
Hi, thanks for your support...

This is more like an opinion-based question related to your domain of analysis.

However, at inference time u need to reproduce all the procedures u compute during the training phase. So if use tsmoothie for filtering the noise you should smooth also the new data points.

**Comment by nsankar** [comment]
@cerlymarco  Thanks.
